<?php

/**
 * NOTE: This file is auto generated by OpenAPI Generator.
 * Do NOT edit it manually. Run `php artisan openapi:generate-server`.
 */

use App\Http\ApiV1\Modules\Books\Controllers\BookController;
use App\Http\ApiV1\Modules\Buyers\Controllers\BuyerController;
use App\Http\ApiV1\Modules\Protocols\Controllers\ProtocolController;
use App\Http\ApiV1\Modules\Sellers\Controllers\SellerController;
use Illuminate\Support\Facades\Route;

Route::get('books/{id}', [BookController::class, 'get']);
Route::put('books/{id}', [BookController::class, 'replace']);
Route::delete('books/{id}', [BookController::class, 'delete']);
Route::patch('books/{id}', [BookController::class, 'patch']);
Route::post('books', [BookController::class, 'create']);
Route::get('sellers/{id}', [SellerController::class, 'get']);
Route::delete('sellers/{id}', [SellerController::class, 'delete']);
Route::patch('sellers/{id}', [SellerController::class, 'patch']);
Route::post('sellers', [SellerController::class, 'create']);
Route::get('buyers/{id}', [BuyerController::class, 'get']);
Route::delete('buyers/{id}', [BuyerController::class, 'delete']);
Route::patch('buyers/{id}', [BuyerController::class, 'patch']);
Route::post('buyers', [BuyerController::class, 'create']);
Route::get('protocols/{id}', [ProtocolController::class, 'get']);
Route::delete('protocols/{id}', [ProtocolController::class, 'delete']);
Route::patch('protocols/{id}', [ProtocolController::class, 'patch']);
Route::post('protocols', [ProtocolController::class, 'create']);
